[package]
name = "bacter"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
wasm-bindgen = { version = "0.2.63", optional = true }
getrandom = { version = "0.2", features = ["js"] } #required to be explicit for wasm-bindgen to compile.

[features]
wasm = ["wasm-bindgen"]
