[package]
name = "bacter-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
bacter = { path = "../bacter" }
# Add any other wasm-specific dependencies here